In [1]:
import pandas as pd
import plotly.express as px
import plotly.io as pio
import os

In [2]:
# Get the current working directory
base_dir = os.getcwd()

# Specify file name and construct the file path
file_name = 'spotify_25.csv'
file_path = os.path.join(base_dir, 'datasets', file_name)

# Check if file exists and load
if os.path.exists(file_path):
    spotify_df = pd.read_csv(file_path)
    print("File loaded successfully.")
    display(spotify_df.head())  # Display the first few rows of the DataFrame
else:
    print(f"File not found: {file_path}")

File loaded successfully.

,title,rank,date,artist,url,region,chart,trend,streams,year
0,Purple Rain,1,2017-02-17,Prince,https://open.spotify.com/track/54X78diSLoUDI3j...,Argentina,viral50,SAME_POSITION,NaN,2017
1,"City Of Stars - From ""La La Land"" Soundtrack",1,2017-01-28,"Ryan Gosling, Emma Stone",https://open.spotify.com/track/0LtVx5vsq9nfpGs...,Mexico,viral50,SAME_POSITION,NaN,2017
2,Sleep Talking,1,2017-10-24,Charlotte Lawrence,https://open.spotify.com/track/0bOH2yZkaVSg2Od...,Brazil,viral50,SAME_POSITION,NaN,2017
3,Despacito (Featuring Daddy Yankee),1,2017-01-30,Luis Fonsi,https://open.spotify.com/track/4aWmUDTfIPGksMN...,Uruguay,top200,SAME_POSITION,33967.0,2017
4,Despacito - Remix,1,2017-04-21,"Luis Fonsi, Daddy Yankee, Justin Bieber",https://open.spotify.com/track/5CtI0qwDJkDQGwX...,Peru,top200,SAME_POSITION,98818.0,2017

In [3]:

spotify_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136453 entries, 0 to 136452
Data columns (total 10 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   title    136453 non-null  object
 1   rank     136453 non-null  int64
 2   date     136453 non-null  object
 3   artist   136453 non-null  object
 4   url      136453 non-null  object
 5   region   136453 non-null  object
 6   chart    136453 non-null  object
 7   trend    136453 non-null  object
 8   streams  122225 non-null  float64
 9   year     136453 non-null  int64
dtypes: float64(1), int64(2), object(7)
memory usage: 10.4+ MB

In [4]:
pd.options.display.float_format = '{:,.2f}'.format
pio.templates.default = "plotly"
pio.templates["plotly"].layout.update(
    width=1000,
    height=600,
    colorway=px.colors.qualitative.Bold
)

Layout({
    'annotationdefaults': {'arrowcolor': '#2a3f5f', 'arrowhead': 0, 'arrowwidth': 1},
    'autotypenumbers': 'strict',
    'coloraxis': {'colorbar': {'outlinewidth': 0, 'ticks': ''}},
    'colorscale': {'diverging': [[0, '#8e0152'], [0.1, '#c51b7d'], [0.2,
                                 '#de77ae'], [0.3, '#f1b6da'], [0.4, '#fde0ef'],
                                 [0.5, '#f7f7f7'], [0.6, '#e6f5d0'], [0.7,
                                 '#b8e186'], [0.8, '#7fbc41'], [0.9, '#4d9221'],
                                 [1, '#276419']],
                   'sequential': [[0.0, '#0d0887'], [0.1111111111111111,
                                  '#46039f'], [0.2222222222222222, '#7201a8'],
                                  [0.3333333333333333, '#9c179e'],
                                  [0.4444444444444444, '#bd3786'],
                                  [0.5555555555555556, '#d8576b'],
                                  [0.6666666666666666, '#ed7953'],
                                  [0.7777777777777778, '#fb9f3a'],
                                  [0.8888888888888888, '#fdca26'], [1.0,
                                  '#f0f921']],
                   'sequentialminus': [[0.0, '#0d0887'], [0.1111111111111111,
                                       '#46039f'], [0.2222222222222222, '#7201a8'],
                                       [0.3333333333333333, '#9c179e'],
                                       [0.4444444444444444, '#bd3786'],
                                       [0.5555555555555556, '#d8576b'],
                                       [0.6666666666666666, '#ed7953'],
                                       [0.7777777777777778, '#fb9f3a'],
                                       [0.8888888888888888, '#fdca26'], [1.0,
                                       '#f0f921']]},
    'colorway': [rgb(127, 60, 141), rgb(17, 165, 121), rgb(57, 105, 172), rgb(242,
                 183, 1), rgb(231, 63, 116), rgb(128, 186, 90), rgb(230, 131, 16),
                 rgb(0, 134, 149), rgb(207, 28, 144), rgb(249, 123, 114), rgb(165,
                 170, 153)],
    'font': {'color': '#2a3f5f'},
    'geo': {'bgcolor': 'white',
            'lakecolor': 'white',
            'landcolor': '#E5ECF6',
            'showlakes': True,
            'showland': True,
            'subunitcolor': 'white'},
    'height': 600,
    'hoverlabel': {'align': 'left'},
    'hovermode': 'closest',
    'mapbox': {'style': 'light'},
    'paper_bgcolor': 'white',
    'plot_bgcolor': '#E5ECF6',
    'polar': {'angularaxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''},
              'bgcolor': '#E5ECF6',
              'radialaxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''}},
    'scene': {'xaxis': {'backgroundcolor': '#E5ECF6',
                        'gridcolor': 'white',
                        'gridwidth': 2,
                        'linecolor': 'white',
                        'showbackground': True,
                        'ticks': '',
                        'zerolinecolor': 'white'},
              'yaxis': {'backgroundcolor': '#E5ECF6',
                        'gridcolor': 'white',
                        'gridwidth': 2,
                        'linecolor': 'white',
                        'showbackground': True,
                        'ticks': '',
                        'zerolinecolor': 'white'},
              'zaxis': {'backgroundcolor': '#E5ECF6',
                        'gridcolor': 'white',
                        'gridwidth': 2,
                        'linecolor': 'white',
                        'showbackground': True,
                        'ticks': '',
                        'zerolinecolor': 'white'}},
    'shapedefaults': {'line': {'color': '#2a3f5f'}},
    'ternary': {'aaxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''},
                'baxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''},
                'bgcolor': '#E5ECF6',
                'caxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''}},
    'title': {'x': 0.05},
    'width': 1000,
    'xaxis': {'automargin': True,
              'gridcolor': 'white',
              'linecolor': 'white',
              'ticks': '',
              'title': {'standoff': 15},
              'zerolinecolor': 'white',
              'zerolinewidth': 2},
    'yaxis': {'automargin': True,
              'gridcolor': 'white',
              'linecolor': 'white',
              'ticks': '',
              'title': {'standoff': 15},
              'zerolinecolor': 'white',
              'zerolinewidth': 2}
})

In [5]:
spotify_df

,title,rank,date,artist,url,region,chart,trend,streams,year
0,Purple Rain,1,2017-02-17,Prince,https://open.spotify.com/track/54X78diSLoUDI3j...,Argentina,viral50,SAME_POSITION,NaN,2017
1,"City Of Stars - From ""La La Land"" Soundtrack",1,2017-01-28,"Ryan Gosling, Emma Stone",https://open.spotify.com/track/0LtVx5vsq9nfpGs...,Mexico,viral50,SAME_POSITION,NaN,2017
2,Sleep Talking,1,2017-10-24,Charlotte Lawrence,https://open.spotify.com/track/0bOH2yZkaVSg2Od...,Brazil,viral50,SAME_POSITION,NaN,2017
3,Despacito (Featuring Daddy Yankee),1,2017-01-30,Luis Fonsi,https://open.spotify.com/track/4aWmUDTfIPGksMN...,Uruguay,top200,SAME_POSITION,"33,967.00",2017
4,Despacito - Remix,1,2017-04-21,"Luis Fonsi, Daddy Yankee, Justin Bieber",https://open.spotify.com/track/5CtI0qwDJkDQGwX...,Peru,top200,SAME_POSITION,"98,818.00",2017
...,...,...,...,...,...,...,...,...,...,...
136448,"10,000 Hours (with Justin Bieber)",131,2021-06-05,Dan + Shay,https://open.spotify.com/track/2wrJq5XKLnmhRXH...,South Korea,top200,MOVE_DOWN,"1,651.00",2021
136449,eight(Prod.&Feat. SUGA of BTS),21,2021-03-17,IU,https://open.spotify.com/track/0pYacDCZuRhcrwG...,South Korea,top200,MOVE_UP,"3,404.00",2021
136450,Spaceman,190,2021-03-17,Nick Jonas,https://open.spotify.com/track/1Tf0qifzTHdDC9R...,South Korea,top200,MOVE_DOWN,"1,028.00",2021
136451,Lovemonth,41,2021-04-13,YUKIKA,https://open.spotify.com/track/5KnAca7g0lgwzCN...,South Korea,viral50,MOVE_DOWN,NaN,2021
136452,Closer,185,2021-09-02,"The Chainsmokers, Halsey",https://open.spotify.com/track/7BKLCZ1jbUBVqRi...,South Korea,top200,MOVE_UP,"1,410.00",2021

In [6]:
# Taylor Swift

In [7]:
ts_df = spotify_df[spotify_df['artist'].str.contains('Taylor Swift', case=False, na=False)]

In [8]:
ts_top200 = ts_df[ts_df['chart'] == 'top200']
num_canciones = ts_top200['title'].nunique()
print("Número total de canciones de Taylor Swift en top200:", num_canciones)

Número total de canciones de Taylor Swift en top200: 161

In [9]:
top10_streams = (ts_df[ts_df['streams'].notna()]
                 .groupby('title', as_index=False)['streams'].sum()
                 .sort_values(by='streams', ascending=False)
                 .head(10))
print("\nListado TOP 10 de canciones por streams:")
top10_streams

Listado TOP 10 de canciones por streams:

                                                 title          streams
59   I Don’t Wanna Live Forever (Fifty Shades Darke... 1,188,881,709.00
74     ME! (feat. Brendon Urie of Panic! At The Disco)   604,471,241.00
124                              You Need To Calm Down   603,204,197.00
69                            Look What You Made Me Do   598,212,296.00
158                                             willow   376,388,882.00
72                                               Lover   341,541,784.00
128                                           cardigan   285,012,009.00
6    All Too Well (10 Minute Version) (Taylor's Ver...   255,513,190.00
0                                     ...Ready For It?   249,985,750.00
32                                            Delicate   239,631,298.00

In [10]:
veces_posicion1 = ts_top200[ts_top200['rank'] == 1].shape[0]
print("\nTotal de veces que Taylor Swift estuvo en la posición 1:", veces_posicion1)

Total de veces que Taylor Swift estuvo en la posición 1: 538

# Christmas Song

In [11]:
# Filter the dataset
filtered_df = spotify_df[
    (spotify_df['title'] == "All I Want for Christmas Is You") &
    (spotify_df['region'] == "Global") &
    (spotify_df['chart'] == "top200") &
    (spotify_df['artist'] == "Mariah Carey")
]

# Show the plot
# Create the bar chart
fig = px.bar(filtered_df, x='date', y='streams', title="Appearance of 'All I Want for Christmas Is You' in Spotify top 200",
             color_discrete_sequence=['#FF0000'])  # Red color for Christmas

# Update y-axis to show values in millions
fig.update_yaxes(tickprefix="M", ticksuffix=" streams", tickformat=".2s")

# Show the plot
fig.show()

In [12]:
latam_countries = ['Argentina', 'Brazil', 'Chile', 'Colombia', 'Mexico', 'Peru', 'Uruguay']
latam_unique_artists_df = spotify_df[spotify_df['region'].isin(latam_countries)].groupby('region')['artist'].nunique().reset_index()

fig_choropleth = px.choropleth(latam_unique_artists_df,
                               locations="region",
                               locationmode="country names",
                               color="artist",
                               hover_name="region",
                               title="Unique Artists in LATAM",
                               projection="natural earth")

fig_choropleth.show()